// Generated by CoffeeScript 1.12.4
(function() {
  var Cell, Column, ContextMenu, GridEdit, Row, Utilities, root,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  Utilities = (function() {
    function Utilities() {}

    Utilities.prototype.setAttributes = function(el, attrs) {
      var key, results, value;
      results = [];
      for (key in attrs) {
        value = attrs[key];
        if (value) {
          results.push(el.setAttribute(key, value));
        } else {
          results.push(void 0);
        }
      }
      return results;
    };

    Utilities.prototype.setStyles = function(el, styles) {
      var key, results, value;
      results = [];
      for (key in styles) {
        value = styles[key];
        results.push(el.style[key] = value + "px");
      }
      return results;
    };

    Utilities.prototype.clearActiveCells = function(table) {
      var activeCell, activeCells, index, j, k, len, len1, redCell, redCells;
      redCells = table.redCells;
      activeCells = table.activeCells;
      if (redCells.length > 0) {
        for (index = j = 0, len = redCells.length; j < len; index = ++j) {
          redCell = redCells[index];
          if (redCell != null) {
            redCell.makeInactive();
          }
        }
        table.redCells = [];
      }
      if (activeCells.length > 0) {
        for (index = k = 0, len1 = activeCells.length; k < len1; index = ++k) {
          activeCell = activeCells[index];
          if (activeCell != null) {
            activeCell.makeInactive();
          }
          if (activeCell != null) {
            activeCell.hideControl();
          }
        }
        table.activeCells = [];
      }
      table.selectionStart = null;
      table.selectionEnd = null;
      table.contextMenu.hide();
      if (table.selectedCol) {
        return table.selectedCol.makeInactive();
      }
    };

    Utilities.prototype.capitalize = function(string) {
      return string.toLowerCase().replace(/\b./g, function(a) {
        return a.toUpperCase();
      });
    };

    return Utilities;

  })();

  GridEdit = (function() {
    function GridEdit(config1) {
      var key, ref, value;
      this.config = config1;
      this.element = document.querySelectorAll(this.config.element || '#gridedit')[0];
      this.headers = [];
      this.rows = [];
      this.cols = [];
      this.source = this.config.rows;
      this.redCells = [];
      this.activeCells = [];
      this.copiedCells = [];
      this.copiedValues = [];
      this.selectionStart = null;
      this.selectionEnd = null;
      this.selectedCol = null;
      this.openCell = null;
      this.state = "ready";
      this.mobile = /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent);
      this.topOffset = !this.config.topOffset ? 0 : this.config.topOffset;
      this.cellStyles = {
        activeColor: "#FFE16F",
        uneditableColor: "#FFBBB3"
      };
      if (this.config.custom) {
        ref = this.config.custom;
        for (key in ref) {
          value = ref[key];
          if (key in this.config.custom) {
            this.set(key, value);
          }
        }
        delete this.config.custom;
      }
      if (this.config.initialize) {
        this.init();
      }
      this.contextMenu = new ContextMenu(['cut', 'copy', 'paste', 'undo', 'fill'], this);
    }

    GridEdit.prototype.init = function() {
      if (this.config.beforeInit) {
        this.config.beforeInit();
      }
      this.build();
      this.events();
      this.render();
      if (this.config.afterInit) {
        this.config.afterInit();
      }
    };

    GridEdit.prototype.build = function() {
      var col, colAttributes, i, j, k, len, len1, ref, ref1, row, rowAttributes, table, tbody, thead, tr;
      tr = document.createElement('tr');
      ref = this.config.cols;
      for (i = j = 0, len = ref.length; j < len; i = ++j) {
        colAttributes = ref[i];
        col = new Column(colAttributes, this);
        this.cols.push(col);
        tr.appendChild(col.element);
      }
      thead = document.createElement('thead');
      thead.appendChild(tr);
      tbody = document.createElement('tbody');
      ref1 = this.source;
      for (i = k = 0, len1 = ref1.length; k < len1; i = ++k) {
        rowAttributes = ref1[i];
        row = new Row(rowAttributes, this);
        this.rows.push(row);
        tbody.appendChild(row.element);
      }
      table = document.createElement('table');
      Utilities.prototype.setAttributes(table, {
        id: 'editable-grid',
        "class": this.config.tableClass
      });
      table.appendChild(thead);
      table.appendChild(tbody);
      return this.tableEl = table;
    };

    GridEdit.prototype.rebuild = function(newConfig) {
      var config, option;
      if (newConfig == null) {
        newConfig = null;
      }
      config = Object.create(this.config);
      if (newConfig !== null) {
        for (option in newConfig) {
          if (newConfig[option]) {
            config[option] = newConfig[option];
          }
        }
      }
      this.destroy();
      return this.constructor(config);
    };

    GridEdit.prototype.events = function() {
      var edit, moveTo, table;
      table = this;
      moveTo = table.moveTo;
      edit = table.edit;
      document.onkeydown = function(e) {
        var cmd, ctrl, key, openCellAndPopulateInitialValue, shift, valueFromKey;
        if (table.activeCell()) {
          key = e.keyCode;
          shift = e.shiftKey;
          ctrl = e.ctrlKey;
          cmd = e.metaKey;
          valueFromKey = function(key, shift) {
            var char;
            char = String.fromCharCode(key);
            if (!shift) {
              return char.toLowerCase();
            } else {
              return char;
            }
          };
          openCellAndPopulateInitialValue = function() {
            if (!table.openCell) {
              return table.activeCell().showControl(valueFromKey(key, shift));
            }
          };
          switch (key) {
            case 39:
              if (!table.activeCell().isBeingEdited()) {
                return moveTo(table.nextCell());
              }
              break;
            case 9:
              if (shift) {
                return moveTo(table.previousCell());
              } else {
                return moveTo(table.nextCell());
              }
              break;
            case 37:
              return moveTo(table.previousCell());
            case 38:
              return moveTo(table.aboveCell());
            case 40:
              return moveTo(table.belowCell());
            case 32:
              if (!table.openCell) {
                return edit(table.activeCell());
              }
              break;
            case 67:
              if (cmd || ctrl) {
                return table.contextMenu.copy();
              } else {
                return openCellAndPopulateInitialValue();
              }
              break;
            case 86:
              if (cmd || ctrl) {
                return table.contextMenu.paste();
              } else {
                return openCellAndPopulateInitialValue();
              }
              break;
            case 88:
              if (cmd || ctrl) {
                return table.contextMenu.cut();
              } else {
                return openCellAndPopulateInitialValue();
              }
              break;
            case 90:
              if (cmd || ctrl) {
                return table.contextMenu.undo();
              } else {
                return openCellAndPopulateInitialValue();
              }
              break;
            case 13:
              break;
            case 16:
              break;
            case 17:
              break;
            case 91:
              break;
            case 8:
              if (!table.openCell) {
                e.preventDefault();
                return table["delete"]();
              }
              break;
            case 46:
              if (!table.openCell) {
                e.preventDefault();
                return table["delete"]();
              }
              break;
            default:
              if (indexOf.call([96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111], key) >= 0) {
                key = key - 48;
              }
              return openCellAndPopulateInitialValue();
          }
        }
      };
      window.onresize = function() {
        if (table.openCell) {
          return Utilities.prototype.setStyles(table.openCell.control, table.openCell.position());
        }
      };
      window.onscroll = function() {
        if (table.openCell) {
          return table.openCell.reposition();
        }
      };
      this.tableEl.oncontextmenu = function(e) {
        return false;
      };
      return document.onclick = function(e) {
        var ref;
        if (!((table.isDescendant(e.target)) || (e.target === ((ref = table.activeCell()) != null ? ref.control : void 0)))) {
          return Utilities.prototype.clearActiveCells(table);
        }
      };
    };

    GridEdit.prototype.render = function() {
      if (this.element.hasChildNodes()) {
        this.element = document.querySelectorAll(this.config.element || '#gridedit')[0];
      }
      return this.element.appendChild(this.tableEl);
    };

    GridEdit.prototype.set = function(key, value) {
      if (key !== void 0) {
        return this.config[key] = value;
      }
    };

    GridEdit.prototype.getCell = function(x, y) {
      return this.rows[x].cells[y];
    };

    GridEdit.prototype.activeCell = function() {
      if (this.activeCells.length > 1) {
        return this.activeCells;
      } else {
        return this.activeCells[0];
      }
    };

    GridEdit.prototype.nextCell = function() {
      var ref;
      return (ref = this.activeCell()) != null ? ref.next() : void 0;
    };

    GridEdit.prototype.previousCell = function() {
      var ref;
      return (ref = this.activeCell()) != null ? ref.previous() : void 0;
    };

    GridEdit.prototype.aboveCell = function() {
      var ref;
      return (ref = this.activeCell()) != null ? ref.above() : void 0;
    };

    GridEdit.prototype.belowCell = function() {
      var ref;
      return (ref = this.activeCell()) != null ? ref.below() : void 0;
    };

    GridEdit.prototype.moveTo = function(toCell, fromCell) {
      var beforeCellNavigateReturnVal, direction, directionModifier, newY, oldY;
      if (toCell) {
        if (fromCell === void 0) {
          fromCell = toCell.table.activeCell();
        }
        direction = toCell.table.getDirection(fromCell, toCell);
        if (toCell.beforeNavigateTo) {
          beforeCellNavigateReturnVal = toCell.beforeNavigateTo(toCell, fromCell, direction);
        }
        if (beforeCellNavigateReturnVal !== false) {
          if (!toCell.isVisible()) {
            oldY = toCell.table.activeCell().address[0];
            newY = toCell.address[0];
            directionModifier = 1;
            if (newY < oldY) {
              directionModifier = -1;
            }
            window.scrollBy(0, (toCell != null ? toCell.position().height : void 0) * directionModifier);
          }
          toCell.makeActive();
        }
      }
      return false;
    };

    GridEdit.prototype.getDirection = function(fromCell, toCell) {
      var direction, fromAddressX, fromAddressY, toAddressX, toAddressY;
      fromAddressY = fromCell.address[0];
      toAddressY = toCell.address[0];
      fromAddressX = fromCell.address[1];
      toAddressX = toCell.address[1];
      if (fromAddressY === toAddressY) {
        if (fromAddressX > toAddressX) {
          direction = "left";
        } else if (fromAddressX < toAddressX) {
          direction = "right";
        } else {
          console.log("Cannot calculate direction going from cell " + fromCell.address + " to cell " + toCell.address);
        }
      } else if (fromAddressY > toAddressY) {
        direction = "up";
      } else if (fromAddressY < toAddressY) {
        direction = "down";
      } else {
        console.log("Cannot calculate direction going from cell " + fromCell.address + " to cell " + toCell.address);
      }
      return direction;
    };

    GridEdit.prototype.edit = function(cell, newValue) {
      if (newValue == null) {
        newValue = null;
      }
      if (newValue !== null) {
        return cell != null ? cell.edit(newValue) : void 0;
      } else {
        if (cell != null) {
          cell.edit();
        }
        return false;
      }
    };

    GridEdit.prototype["delete"] = function() {
      var cell, j, len, ref, results;
      ref = this.activeCells;
      results = [];
      for (j = 0, len = ref.length; j < len; j++) {
        cell = ref[j];
        results.push(cell.value(''));
      }
      return results;
    };

    GridEdit.prototype.clearActiveCells = function() {
      return Utilities.prototype.clearActiveCells(this);
    };

    GridEdit.prototype.setSelection = function() {
      var cell, col, colRange, j, k, l, len, len1, len2, m, n, ref, ref1, ref2, ref3, ref4, results, results1, row, rowRange;
      if (this.selectionStart !== this.selectionEnd) {
        ref = this.activeCells;
        for (j = 0, len = ref.length; j < len; j++) {
          cell = ref[j];
          cell.removeFromSelection();
        }
        this.activeCells = [];
        rowRange = (function() {
          results = [];
          for (var k = ref1 = this.selectionStart.address[0], ref2 = this.selectionEnd.address[0]; ref1 <= ref2 ? k <= ref2 : k >= ref2; ref1 <= ref2 ? k++ : k--){ results.push(k); }
          return results;
        }).apply(this);
        colRange = (function() {
          results1 = [];
          for (var l = ref3 = this.selectionStart.address[1], ref4 = this.selectionEnd.address[1]; ref3 <= ref4 ? l <= ref4 : l >= ref4; ref3 <= ref4 ? l++ : l--){ results1.push(l); }
          return results1;
        }).apply(this);
        for (m = 0, len1 = rowRange.length; m < len1; m++) {
          row = rowRange[m];
          for (n = 0, len2 = colRange.length; n < len2; n++) {
            col = colRange[n];
            this.rows[row].cells[col].addToSelection();
          }
        }
      }
    };

    GridEdit.prototype.data = function() {
      var cell, data, j, k, len, len1, ref, ref1, row, rowData;
      data = [];
      ref = this.rows;
      for (j = 0, len = ref.length; j < len; j++) {
        row = ref[j];
        rowData = [];
        ref1 = row.cells;
        for (k = 0, len1 = ref1.length; k < len1; k++) {
          cell = ref1[k];
          rowData.push(cell.type === 'date' ? cell.control.valueAsDate : cell.value());
        }
        data.push(rowData);
      }
      return data;
    };

    GridEdit.prototype.repopulate = function() {
      var cell, j, len, ref, results, row;
      ref = this.rows;
      results = [];
      for (j = 0, len = ref.length; j < len; j++) {
        row = ref[j];
        results.push((function() {
          var k, len1, ref1, results1;
          ref1 = row.cells;
          results1 = [];
          for (k = 0, len1 = ref1.length; k < len1; k++) {
            cell = ref1[k];
            results1.push(cell.value(cell.source[cell.valueKey]));
          }
          return results1;
        })());
      }
      return results;
    };

    GridEdit.prototype.destroy = function() {
      var key, results;
      this.element.removeChild(this.tableEl);
      results = [];
      for (key in this) {
        results.push(delete this[key]);
      }
      return results;
    };

    GridEdit.prototype.isDescendant = function(child) {
      var node;
      node = child.parentNode;
      while (node != null) {
        if (node === this.tableEl) {
          return true;
        }
        node = node.parentNode;
      }
      return false;
    };

    return GridEdit;

  })();

  Column = (function() {
    function Column(attributes, table1) {
      var key, ref, value;
      this.attributes = attributes;
      this.table = table1;
      this.id = this.index = this.table.cols.length;
      this.cells = [];
      this.element = document.createElement('th');
      this.textNode = document.createTextNode(this.attributes.label);
      this.element.appendChild(this.textNode);
      ref = this.attributes;
      for (key in ref) {
        value = ref[key];
        this[key] = value;
      }
      delete this.attributes;
      this.events();
    }

    Column.prototype.next = function() {
      return this.table.cols[this.index + 1];
    };

    Column.prototype.previous = function() {
      return this.table.cols[this.index - 1];
    };

    Column.prototype.makeActive = function() {
      this.element.classList.add('active');
      return this.table.selectedCol = this;
    };

    Column.prototype.makeInactive = function() {
      this.element.classList.remove('active');
      return this.table.selectedCol = null;
    };

    Column.prototype.events = function() {
      var col, table;
      col = this;
      table = col.table;
      this.element.onclick = function(e) {
        var cell, j, len, ref, results;
        Utilities.prototype.clearActiveCells(table);
        col.makeActive();
        ref = col.cells;
        results = [];
        for (j = 0, len = ref.length; j < len; j++) {
          cell = ref[j];
          results.push(cell.addToSelection());
        }
        return results;
      };
      return this.element.onmousedown = function(e) {
        if (e.which === 3) {
          table.contextMenu.show(e.x, e.y, col.cells[0]);
          return;
        }
        return false;
      };
    };

    return Column;

  })();

  Row = (function() {
    function Row(attributes, table1) {
      var cell, col, i, j, len, ref;
      this.attributes = attributes;
      this.table = table1;
      this.id = this.table.rows.length;
      this.cells = [];
      this.index = this.table.rows.length;
      this.element = document.createElement('tr');
      this.editable = true;
      Utilities.prototype.setAttributes(this.element, {
        id: "row-" + this.id
      });
      ref = this.table.cols;
      for (i = j = 0, len = ref.length; j < len; i = ++j) {
        col = ref[i];
        cell = new Cell(this.attributes[col.valueKey], this);
        this.cells.push(cell);
        this.table.cols[i].cells.push(cell);
        this.element.appendChild(cell.element);
      }
      delete this.attributes;
    }

    Row.prototype.below = function() {
      return this.table.rows[this.index + 1];
    };

    Row.prototype.above = function() {
      return this.table.rows[this.index - 1];
    };

    return Row;

  })();

  Cell = (function() {
    function Cell(attributes, row1) {
      var node, ref, ref1, styleName;
      this.attributes = attributes;
      this.row = row1;
      this.id = this.row.id + "-" + this.row.cells.length;
      this.address = [this.row.id, this.row.cells.length];
      this.index = this.row.cells.length;
      this.table = this.row.table;
      this.col = this.table.cols[this.index];
      this.type = this.col.type;
      this.meta = this.col;
      if ('editable' in this.col) {
        this.editable = this.col.editable;
      } else {
        this.editable = true;
      }
      this.element = document.createElement('td');
      this.originalValue = this.attributes;
      this.val = this.originalValue;
      this.values = [this.originalValue];
      this.previousValue = null;
      this.valueKey = this.col.valueKey;
      this.source = this.table.config.rows[this.address[0]];
      this.initCallbacks();
      Utilities.prototype.setAttributes(this.element, {
        id: "cell-" + this.id,
        "class": ((ref = this.attributes) != null ? ref["class"] : void 0) || '',
        style: ((ref1 = this.attributes) != null ? ref1.styles : void 0) || ''
      });
      if (this.col.style) {
        for (styleName in this.col.style) {
          this.element.style[styleName] = this.col.style[styleName];
        }
      }
      switch (this.type) {
        case 'string':
          node = document.createTextNode(this.attributes);
          this.control = document.createElement('input');
          break;
        case 'number':
          node = document.createTextNode(this.attributes);
          this.control = document.createElement('input');
          break;
        case 'date':
          node = document.createTextNode(this.toDateString(this.attributes));
          this.control = this.toDate();
          if (this.originalValue) {
            this.control.valueAsDate = new Date(this.originalValue);
          }
          break;
        case 'html':
          this.htmlContent = this.attributes;
          node = this.toFragment();
          this.control = document.createElement('input');
          break;
        case 'select':
          node = document.createTextNode(this.attributes || '');
          this.control = this.toSelect();
      }
      this.element.appendChild(node);
      delete this.attributes;
      this.events(this);
    }

    Cell.prototype.initCallbacks = function() {
      if (this.table.config.beforeEdit) {
        this.beforeEdit = this.table.config.beforeEdit;
      }
      if (this.table.config.afterEdit) {
        this.afterEdit = this.table.config.afterEdit;
      }
      if (this.table.config.beforeCellActivate) {
        this.beforeActivate = this.table.config.beforeCellActivate;
      }
      if (this.table.config.afterCellActivate) {
        this.afterActivate = this.table.config.afterCellActivate;
      }
      if (this.table.config.beforeControlInit) {
        this.beforeControlInit = this.table.config.beforeControlInit;
      }
      if (this.table.config.afterControlInit) {
        this.afterControlInit = this.table.config.afterControlInit;
      }
      if (this.table.config.beforeControlHide) {
        this.beforeControlHide = this.table.config.beforeControlHide;
      }
      if (this.table.config.afterControlHide) {
        this.afterControlHide = this.table.config.afterControlHide;
      }
      if (this.table.config.onCellClick) {
        this.onClick = this.table.config.onCellClick;
      }
      if (this.table.config.beforeCellNavigateTo) {
        return this.beforeNavigateTo = this.table.config.beforeCellNavigateTo;
      }
    };

    Cell.prototype.setNewHTMLValue = function(newValue) {
      var node;
      this.htmlContent = newValue;
      node = this.toFragment();
      this.element.innerHTML = "";
      return this.element.appendChild(node);
    };

    Cell.prototype.value = function(newValue) {
      var oldValue;
      if (newValue == null) {
        newValue = null;
      }
      if (newValue !== null && newValue !== this.element.textContent) {
        if (this.type === 'date') {
          if (newValue.length > 0) {
            newValue = this.toDateString(Date.parse(newValue));
          } else if (newValue instanceof Date) {
            newValue = this.toDateString(newValue);
          } else if (newValue.length === 0) {
            newValue = "";
            this.control.valueAsDate = null;
          }
        } else if (this.type === 'number') {
          if (newValue.length === 0) {
            newValue = null;
          } else {
            newValue = Number(newValue);
          }
        }
        oldValue = this.value();
        if (this.beforeEdit) {
          this.beforeEdit(this, oldValue, newValue);
        }
        this.previousValue = this.element.textContent;
        this.values.push(newValue);
        this.element.textContent = newValue;
        if (this.type === 'number') {
          this.source[this.valueKey] = Number(newValue);
        } else if (this.type === 'date') {
          this.source[this.valueKey] = new Date(newValue);
          this.control.valueAsDate = new Date(newValue);
        } else if (this.type === 'html') {
          this.setNewHTMLValue(newValue);
        } else {
          this.source[this.valueKey] = newValue;
        }
        Utilities.prototype.setStyles(this.control, this.position());
        if (this.afterEdit) {
          this.afterEdit(this, oldValue, newValue, this.table.contextMenu.getTargetPasteCell());
        }
        return newValue;
      } else {
        if (this.type !== 'html') {
          return this.element.textContent;
        } else {
          return this.htmlContent;
        }
      }
    };

    Cell.prototype.makeActive = function() {
      var beforeActivateReturnVal;
      if (this.beforeActivate) {
        beforeActivateReturnVal = this.beforeActivate(this);
      }
      if (this.beforeActivate && beforeActivateReturnVal !== false || !this.beforeActivate) {
        Utilities.prototype.clearActiveCells(this.table);
        this.showActive();
        this.table.activeCells.push(this);
        this.table.selectionStart = this;
        if (this.table.openCell) {
          this.table.openCell.edit(this.table.openCell.control.value);
        }
        if (this.afterActivate) {
          return this.afterActivate(this);
        }
      }
    };

    Cell.prototype.makeInactive = function() {
      return this.showInactive();
    };

    Cell.prototype.addToSelection = function() {
      this.showActive();
      return this.table.activeCells.push(this);
    };

    Cell.prototype.isActive = function() {
      return this.table.activeCells.indexOf(this) !== -1;
    };

    Cell.prototype.removeFromSelection = function() {
      return this.showInactive();
    };

    Cell.prototype.showActive = function() {
      var cssText;
      cssText = this.element.style.cssText;
      this.oldCssText = cssText;
      return this.element.style.cssText = cssText + ' ' + ("background-color: " + this.table.cellStyles.activeColor + ";");
    };

    Cell.prototype.showInactive = function() {
      return this.element.style.cssText = this.oldCssText;
    };

    Cell.prototype.showRed = function() {
      this.element.style.cssText = "background-color: " + this.table.cellStyles.uneditableColor + ";";
      return this.table.redCells.push(this);
    };

    Cell.prototype.showControl = function(value) {
      var beforeControlInitReturnVal, cell, control;
      if (value == null) {
        value = null;
      }
      if (this.table.contextMenu.borderedCells.length > 0) {
        this.table.contextMenu.hideBorders();
      }
      if (!this.editable) {
        return this.showRed();
      } else {
        if (this.beforeControlInit) {
          beforeControlInitReturnVal = this.beforeControlInit(this);
        }
        if (this.beforeControlInit && beforeControlInitReturnVal !== false || !this.beforeControlInit) {
          if (value !== null) {
            this.control.value = value;
            control = this.control;
            setTimeout(function() {
              return control.focus();
            }, 0);
          } else {
            if (this.type === 'select') {
              this.control = this.toSelect();
              cell = this;
              this.control.onchange = function(e) {
                return cell.edit(e.target.value);
              };
            } else {
              this.control.value = this.value();
            }
          }
          if (this.type === 'date') {
            this.control.value = this.toDateInputString(this.value());
          }
          this.control.style.position = "fixed";
          Utilities.prototype.setStyles(this.control, this.position());
          this.table.element.appendChild(this.control);
          this.table.openCell = this;
          if (this.afterControlInit) {
            return this.afterControlInit(this);
          }
        }
      }
    };

    Cell.prototype.hideControl = function() {
      var beforeControlHideReturnVal;
      if (this.table.openCell !== null) {
        if (this.beforeControlHide) {
          beforeControlHideReturnVal = this.beforeControlHide(this);
        }
        if (this.beforeControlHide && beforeControlHideReturnVal !== false || !this.beforeControlHide) {
          if (this.isControlInDocument()) {
            this.control.remove();
          }
        }
        this.table.openCell = null;
        if (this.afterControlHide) {
          return this.afterControlHide(this);
        }
      }
    };

    Cell.prototype.edit = function(newValue) {
      if (newValue == null) {
        newValue = null;
      }
      if (!this.editable) {
        return this.showRed();
      } else {
        if (newValue !== null) {
          this.value(newValue);
          if (this.isBeingEdited()) {
            return this.hideControl();
          } else {
            return this.edit();
          }
        } else {
          this.showControl();
          this.control.focus();
          if (this.type !== 'select') {
            return this.control.select();
          }
        }
      }
    };

    Cell.prototype.position = function() {
      return this.element.getBoundingClientRect();
    };

    Cell.prototype.isVisible = function() {
      var position;
      position = this.position();
      return (position.top >= this.table.topOffset) && (position.bottom <= window.innerHeight);
    };

    Cell.prototype.isControlInDocument = function() {
      return this.control.parentNode !== null;
    };

    Cell.prototype.reposition = function() {
      return Utilities.prototype.setStyles(this.control, this.position());
    };

    Cell.prototype.next = function() {
      var ref;
      return this.row.cells[this.index + 1] || ((ref = this.row.below()) != null ? ref.cells[0] : void 0);
    };

    Cell.prototype.previous = function() {
      var ref;
      return this.row.cells[this.index - 1] || ((ref = this.row.above()) != null ? ref.cells[this.row.cells.length - 1] : void 0);
    };

    Cell.prototype.above = function() {
      var ref;
      return (ref = this.row.above()) != null ? ref.cells[this.index] : void 0;
    };

    Cell.prototype.below = function() {
      var ref;
      return (ref = this.row.below()) != null ? ref.cells[this.index] : void 0;
    };

    Cell.prototype.isBefore = function(cell) {
      return cell.address[0] === this.address[0] && cell.address[1] > this.address[1];
    };

    Cell.prototype.isAfter = function(cell) {
      return cell.address[0] === this.address[0] && cell.address[1] < this.address[1];
    };

    Cell.prototype.isAbove = function(cell) {
      return cell.address[0] > this.address[0] && cell.address[1] === this.address[1];
    };

    Cell.prototype.isBelow = function(cell) {
      return cell.address[0] < this.address[0] && cell.address[1] === this.address[1];
    };

    Cell.prototype.addClass = function(newClass) {
      return this.element.classList.add(newClass);
    };

    Cell.prototype.removeClass = function(classToRemove) {
      return this.element.classList.remove(classToRemove);
    };

    Cell.prototype.toFragment = function() {
      var element, fragment;
      element = document.createElement("div");
      fragment = document.createDocumentFragment();
      element.innerHTML = this.htmlContent;
      fragment.appendChild(element.firstChild || document.createTextNode(''));
      return fragment;
    };

    Cell.prototype.toSelect = function() {
      var choice, index, j, k, len, len1, option, ref, select, subchoice;
      select = document.createElement("select");
      if (!this.meta.choices) {
        console.log("There is not a 'choices' key in cell " + this.address + " and you specified that it was of type 'select'");
      }
      ref = this.meta.choices;
      for (j = 0, len = ref.length; j < len; j++) {
        choice = ref[j];
        option = document.createElement("option");
        if (choice instanceof Array) {
          for (index = k = 0, len1 = choice.length; k < len1; index = ++k) {
            subchoice = choice[index];
            if (index === 0) {
              option.value = subchoice;
            }
            if (index === 1) {
              option.text = subchoice;
            }
          }
        } else {
          option.value = option.text = choice;
        }
        if (this.value() === choice) {
          option.selected = true;
        }
        select.add(option);
      }
      select.classList.add('form-control');
      return select;
    };

    Cell.prototype.toDateString = function(passedDate) {
      var date;
      if (passedDate == null) {
        passedDate = null;
      }
      if (passedDate && passedDate !== '') {
        date = new Date(passedDate);
      } else {
        if (this.value()) {
          date = new Date(this.value());
        } else {
          null;
        }
      }
      if (date instanceof Date) {
        return ('0' + (date.getMonth() + 1)).slice(-2) + '-' + ('0' + date.getDate()).slice(-2) + '-' + date.getFullYear();
      } else {
        return '';
      }
    };

    Cell.prototype.toDate = function() {
      var input;
      input = document.createElement('input');
      input.type = 'date';
      input.value = this.toDateString();
      return input;
    };

    Cell.prototype.toDateInputString = function(passedDate) {
      var date;
      if (passedDate == null) {
        passedDate = null;
      }
      if (passedDate && passedDate !== '') {
        date = new Date(passedDate);
      } else {
        if (this.value()) {
          date = new Date(this.value());
        } else {
          null;
        }
      }
      if (date instanceof Date) {
        return date.getFullYear() + '-' + ('0' + (date.getMonth() + 1)).slice(-2) + '-' + ('0' + date.getDate()).slice(-2);
      } else {
        return '';
      }
    };

    Cell.prototype.isBeingEdited = function() {
      return this.control.parentNode != null;
    };

    Cell.prototype.events = function(cell) {
      var activeCells, redCells, startY, table;
      table = cell.table;
      redCells = table.redCells;
      activeCells = table.activeCells;
      this.element.onclick = function(e) {
        var onClickReturnVal;
        if (cell.onClick) {
          onClickReturnVal = cell.onClick(cell, e);
        }
        if (onClickReturnVal === false) {
          return false;
        }
      };
      this.element.ondblclick = function() {
        return cell.edit();
      };
      this.element.onmousedown = function(e) {
        if (e.which === 3) {
          table.contextMenu.show(e.x, e.y, cell);
          return;
        }
        table.state = "selecting";
        cell.makeActive();
        return false;
      };
      this.element.onmouseover = function(e) {
        if (table.state === 'selecting') {
          table.selectionEnd = cell;
          return table.setSelection();
        }
      };
      this.element.onmouseup = function(e) {
        if (e.which !== 3) {
          table.selectionEnd = cell;
          table.setSelection();
          return table.state = "ready";
        }
      };
      this.control.onkeydown = function(e) {
        var key, ref;
        key = e.which;
        switch (key) {
          case 13:
            cell.edit(this.value);
            return (ref = cell.below()) != null ? ref.makeActive() : void 0;
        }
      };
      if (this.type === 'select' || this.type === 'date') {
        this.control.onchange = function(e) {
          return cell.edit(e.target.value);
        };
      }
      if (table.mobile) {
        startY = null;
        this.element.ontouchstart = function(e) {
          startY = e.changedTouches[0].clientY;
          Utilities.prototype.clearActiveCells(table);
          if (table.openCell) {
            return table.openCell.hideControl();
          }
        };
        return this.element.ontouchend = function(e) {
          var y;
          y = e.changedTouches[0].clientY;
          if (e.changedTouches.length < 2 && (y === startY)) {
            e.preventDefault();
            return cell.edit();
          }
        };
      }
    };

    return Cell;

  })();

  ContextMenu = (function() {
    function ContextMenu(actions, table1) {
      var a, action, divider, j, len, li, ref, ul;
      this.actions = actions;
      this.table = table1;
      this.defaultActions = ['cut', 'copy', 'paste', 'undo', 'fill'];
      this.element = document.createElement('div');
      this.actionNodes = {};
      this.borderedCells = [];
      Utilities.prototype.setAttributes(this.element, {
        id: 'contextMenu',
        "class": 'dropdown clearfix'
      });
      ul = document.createElement('ul');
      Utilities.prototype.setAttributes(ul, {
        "class": 'dropdown-menu',
        role: 'menu',
        'aria-labelledby': 'aria-labelledby',
        style: 'display:block;position:static;margin-bottom:5px;'
      });
      ref = this.defaultActions;
      for (j = 0, len = ref.length; j < len; j++) {
        action = ref[j];
        li = document.createElement('li');
        divider = document.createElement('li');
        Utilities.prototype.setAttributes(divider, {
          "class": 'divider'
        });
        a = document.createElement('a');
        a.textContent = Utilities.prototype.capitalize(action);
        if (indexOf.call(this.actions, action) >= 0) {
          Utilities.prototype.setAttributes(a, {
            "class": 'enabled',
            tabIndex: '-1'
          });
        } else {
          Utilities.prototype.setAttributes(a, {
            "class": 'disabled',
            tabIndex: '-1'
          });
        }
        if (action === 'fill') {
          ul.appendChild(divider);
        }
        this.actionNodes[action] = a;
        li.appendChild(a);
        ul.appendChild(li);
      }
      this.element.appendChild(ul);
      this.events(this);
    }

    ContextMenu.prototype.show = function(x, y, cell) {
      if (!cell.isActive()) {
        cell.makeActive();
      }
      this.cells = cell.table.activeCells;
      Utilities.prototype.setStyles(this.element, {
        left: x,
        top: y
      });
      return this.table.tableEl.appendChild(this.element);
    };

    ContextMenu.prototype.hide = function() {
      if (this.isVisible()) {
        return this.table.tableEl.removeChild(this.element);
      }
    };

    ContextMenu.prototype.isVisible = function() {
      return this.element.parentNode != null;
    };

    ContextMenu.prototype.getTargetPasteCell = function() {
      return this.table.activeCells.sort(this.sortFunc)[0];
    };

    ContextMenu.prototype.sortFunc = function(a, b) {
      return a.address[0] - b.address[0];
    };

    ContextMenu.prototype.displayBorders = function() {
      var cell, index, j, len, ref, results;
      this.borderedCells = this.table.activeCells;
      if (this.borderedCells.length > 1) {
        ref = this.borderedCells;
        results = [];
        for (index = j = 0, len = ref.length; j < len; index = ++j) {
          cell = ref[index];
          if (index === 0) {
            cell.element.style.borderTop = "2px dashed blue";
            cell.element.style.borderLeft = "2px dashed blue";
            results.push(cell.element.style.borderRight = "2px dashed blue");
          } else if (index === this.table.activeCells.length - 1) {
            cell.element.style.borderBottom = "2px dashed blue";
            cell.element.style.borderLeft = "2px dashed blue";
            results.push(cell.element.style.borderRight = "2px dashed blue");
          } else {
            cell.element.style.borderLeft = "2px dashed blue";
            results.push(cell.element.style.borderRight = "2px dashed blue");
          }
        }
        return results;
      } else {
        return this.borderedCells[0].element.style.border = "2px dashed blue";
      }
    };

    ContextMenu.prototype.hideBorders = function() {
      var cell, index, j, len, ref;
      ref = this.borderedCells;
      for (index = j = 0, len = ref.length; j < len; index = ++j) {
        cell = ref[index];
        cell.element.style.border = "";
      }
      this.borderedCells = [];
      this.table.copiedValues = [];
      return this.table.copiedCells = [];
    };

    ContextMenu.prototype.cut = function() {
      var beforeActionReturnVal, cell, j, len, ref;
      beforeActionReturnVal = this.beforeAction('cut');
      if (beforeActionReturnVal) {
        this.table.copiedValues = [];
        this.table.copiedCells = this.table.activeCells;
        ref = this.table.activeCells;
        for (j = 0, len = ref.length; j < len; j++) {
          cell = ref[j];
          this.table.copiedValues.push(cell.value());
          cell.value('');
        }
        return this.afterAction('cut');
      }
    };

    ContextMenu.prototype.copy = function() {
      var beforeActionReturnVal, cell, j, len, ref;
      beforeActionReturnVal = this.beforeAction('copy');
      if (beforeActionReturnVal) {
        this.table.copiedValues = [];
        this.table.copiedCells = this.table.activeCells;
        ref = this.table.activeCells;
        for (j = 0, len = ref.length; j < len; j++) {
          cell = ref[j];
          this.table.copiedValues.push(cell.value());
        }
        return this.afterAction('copy');
      }
    };

    ContextMenu.prototype.paste = function() {
      var activeCell, beforeActionReturnVal, cell, index, j, k, len, len1, ref, ref1, value;
      beforeActionReturnVal = this.beforeAction('paste');
      if (beforeActionReturnVal) {
        cell = this.getTargetPasteCell();
        if (this.table.copiedValues.length > 1) {
          ref = this.table.copiedValues;
          for (index = j = 0, len = ref.length; j < len; index = ++j) {
            value = ref[index];
            cell.value(this.table.copiedValues[index]);
            cell = cell.below();
          }
        } else {
          ref1 = this.table.activeCells;
          for (index = k = 0, len1 = ref1.length; k < len1; index = ++k) {
            activeCell = ref1[index];
            activeCell.value(this.table.copiedValues[0]);
          }
        }
        return this.afterAction('paste');
      }
    };

    ContextMenu.prototype.undo = function() {
      var beforeActionReturnVal, value;
      beforeActionReturnVal = this.beforeAction('undo');
      if (beforeActionReturnVal) {
        value = this.cell.values.pop();
        this.cell.value(value);
        return this.afterAction('undo');
      }
    };

    ContextMenu.prototype.fill = function() {
      var beforeActionReturnVal, cell, index, j, len, ref, value;
      beforeActionReturnVal = this.beforeAction('fill');
      if (beforeActionReturnVal) {
        value = this.getTargetPasteCell().value();
        ref = this.table.activeCells;
        for (index = j = 0, len = ref.length; j < len; index = ++j) {
          cell = ref[index];
          cell.value(value);
        }
        return this.afterAction('fill');
      }
    };

    ContextMenu.prototype.beforeAction = function(action) {
      switch (action) {
        case 'cut':
          return true;
        case 'copy':
          return true;
        case 'paste':
          if (this.getTargetPasteCell().editable) {
            return true;
          } else {
            return false;
          }
          break;
        case 'undo':
          return true;
        case 'fill':
          if (this.getTargetPasteCell().editable) {
            return true;
          } else {
            return false;
          }
      }
    };

    ContextMenu.prototype.afterAction = function(action) {
      switch (action) {
        case 'cut':
          this.displayBorders();
          break;
        case 'copy':
          this.displayBorders();
          break;
        case 'paste':
          this.hideBorders();
          break;
        case 'undo':
          break;
        case 'fill':
          break;
      }
      return this.hide();
    };

    ContextMenu.prototype.toggle = function(action) {
      var classes;
      classes = this.actionNodes[action].classList;
      classes.toggle('enabled');
      return classes.toggle('disabled');
    };

    ContextMenu.prototype.events = function(menu) {
      return this.element.onclick = function(e) {
        var action;
        action = e.target.textContent;
        switch (action) {
          case 'Cut':
            return menu.cut();
          case 'Copy':
            return menu.copy();
          case 'Paste':
            return menu.paste();
          case 'Undo':
            return menu.undo();
          case 'Fill':
            return menu.fill();
        }
      };
    };

    return ContextMenu;

  })();

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.GridEdit = GridEdit;

}).call(this);
